server:
  port: 7602

spring:
  application:
    name: provider

  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1
  sleuth:
    sampler:
      rate: 1
# Eureka 公共配置
eureka:
  client:
    # 开启健康检测
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:123456@117.51.140.37:7500/eureka/,http://root:123456@47.93.54.81:7501/eureka/

